spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    generateDdl: true
    show-sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${pghost}:${pgport}/solid
    username: ${pguser}
    password: ${pgpasswd}
    driver-class: org.postgresql.Driver
appConfig: 
    restEndpoint: https://geocode.xyz/{ADR}?geoit=json&auth=${geocodeKey}
    timeout: 60
 